# Generated by Django 4.2.6 on 2023-11-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='food_category',
            new_name='meal_category',
        ),
    ]
